#idempiereEnv.properties
#Wed Mar 04 14:26:19 UTC 2026
ADEMPIERE_DB_SERVER=marselladatabase.postgres.database.azure.com
ADEMPIERE_APPS_SERVER=0.0.0.0
ADEMPIERE_DB_VERSION=2024-12-24
ADEMPIERE_FTP_PASSWORD=user@host.com
IDEMPIERE_JAVA_OPTIONS=-Xms64M -Xmx512M
ADEMPIERE_KEYSTORECODEALIAS=idempiere
ADEMPIERE_DATE_VERSION=2024-12-24
ADEMPIERE_DB_NAME=sannet
JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
ADEMPIERE_DB_USER=adempiere
ADEMPIERE_MAIN_VERSION=Release 12
ADEMPIERE_DB_EXISTS=Y
ADEMPIERE_MAIL_SERVER=localhost
ADEMPIERE_KEYSTOREWEBALIAS=idempiere
ADEMPIERE_DB_URL=jdbc\:postgresql\://marselladatabase.postgres.database.azure.com\:5432/sannet
ADEMPIERE_WEB_PORT=8080
ADEMPIERE_MAIL_USER=
ADEMPIERE_KEYSTORE=/opt/idempiere-server/jettyhome/etc/keystore
ADEMPIERE_DB_PATH=postgresql
ADEMPIERE_FTP_SERVER=localhost
ADEMPIERE_WEB_ALIAS=cargabd.internal.cloudapp.net
ADEMPIERE_MAIL_UPDATED=
ADEMPIERE_ADMIN_EMAIL=
ADEMPIERE_KEYSTOREPASS=OBF\:1saj1vg11t331vgj1xfj1vgb1t331vgt1sar
ADEMPIERE_FTP_USER=anonymous
ADEMPIERE_SSL_PORT=8443
ADEMPIERE_DB_PORT=5432
ADEMPIERE_DB_SYSTEM_USER=
ADEMPIERE_FTP_PREFIX=my
ADEMPIERE_DB_TYPE=PostgreSQL
IDEMPIERE_HOME=/opt/idempiere-server
